[2022-05-20 15:34:57.927] [remoteagent] [info] Extension host agent started.
[2022-05-20 15:34:58.940] [remoteagent] [info] [127.0.0.1][38fea2fa][ManagementConnection] New connection established.
[2022-05-20 15:34:59.296] [remoteagent] [info] [127.0.0.1][ee1ac732][ExtensionHostConnection] New connection established.
[2022-05-20 15:34:59.300] [remoteagent] [info] [127.0.0.1][ee1ac732][ExtensionHostConnection] <160290> Launched Extension Host Process.
[2022-05-20 15:35:00.127] [remoteagent] [info] [127.0.0.1][38fea2fa][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-05-20 15:35:08.583] [remoteagent] [info] [127.0.0.1][4cb96d70][ManagementConnection] New connection established.
[2022-05-20 15:35:08.931] [remoteagent] [info] [127.0.0.1][b03117ce][ExtensionHostConnection] New connection established.
[2022-05-20 15:35:08.953] [remoteagent] [info] [127.0.0.1][b03117ce][ExtensionHostConnection] <160426> Launched Extension Host Process.
[2022-05-20 15:35:20.235] [remoteagent] [info] Getting Manifest... ms-python.vscode-pylance
[2022-05-20 15:35:20.536] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2022-05-20 15:35:23.592] [remoteagent] [info] Downloaded extension: ms-python.vscode-pylance /home/ubuntu/.vscode-server/data/CachedExtensionVSIXs/ms-python.vscode-pylance-2022.5.2
[2022-05-20 15:35:48.436] [remoteagent] [info] Extracted extension to /home/ubuntu/.vscode-server/extensions/.17bc8f04-27d8-4cfc-b701-d806ec8b6d44: ms-python.vscode-pylance
[2022-05-20 15:35:48.528] [remoteagent] [info] Renamed to /home/ubuntu/.vscode-server/extensions/ms-python.vscode-pylance-2022.5.2
[2022-05-20 15:35:48.532] [remoteagent] [info] Extracting completed. ms-python.vscode-pylance
[2022-05-20 15:35:48.538] [remoteagent] [info] Extension installed successfully: ms-python.vscode-pylance
[2022-05-20 15:40:08.860] [remoteagent] [info] [127.0.0.1][ee1ac732][ExtensionHostConnection] <160290> Extension Host Process exited with code: 0, signal: null.
[2022-05-20 19:02:26.228] [remoteagent] [info] [127.0.0.1][b75a62db][ManagementConnection] New connection established.
[2022-05-20 19:02:26.381] [remoteagent] [info] [127.0.0.1][37d99d4c][ExtensionHostConnection] New connection established.
[2022-05-20 19:02:26.400] [remoteagent] [info] [127.0.0.1][37d99d4c][ExtensionHostConnection] <163898> Launched Extension Host Process.
[2022-05-20 19:07:21.106] [remoteagent] [info] [127.0.0.1][b75a62db][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-05-20 19:07:21.125] [remoteagent] [info] [127.0.0.1][37d99d4c][ExtensionHostConnection] <163898> Extension Host Process exited with code: 0, signal: null.
[2022-05-20 19:07:50.569] [remoteagent] [info] [127.0.0.1][77b61f2b][ManagementConnection] New connection established.
[2022-05-20 19:07:50.918] [remoteagent] [info] [127.0.0.1][8700c5b7][ExtensionHostConnection] New connection established.
[2022-05-20 19:07:50.925] [remoteagent] [info] [127.0.0.1][8700c5b7][ExtensionHostConnection] <164392> Launched Extension Host Process.
[2022-05-20 19:09:10.448] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/ubuntu/env/lib/python3.8/site-packages)
[2022-05-20 19:09:10.449] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-05-20 19:19:38.453] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/ubuntu/env/lib/python3.8/site-packages)
[2022-05-20 19:19:38.454] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-05-20 19:19:39.750] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: No such file or directory (EUNKNOWN) (path: /home/ubuntu/env/lib/python3.8/site-packages)
[2022-05-20 19:19:39.750] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: No such file or directory
[2022-05-20 19:20:22.538] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/ubuntu/env/lib/python3.8/site-packages)
[2022-05-20 19:20:22.538] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-05-20 19:20:23.332] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: inotify_add_watch on '/home/ubuntu/env/lib/python3.8/site-packages/~jango/conf/locale/ca' failed: No such file or directory (EUNKNOWN) (path: /home/ubuntu/env/lib/python3.8/site-packages)
[2022-05-20 19:20:23.333] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: inotify_add_watch on '/home/ubuntu/env/lib/python3.8/site-packages/~jango/conf/locale/ca' failed: No such file or directory
[2022-05-20 20:18:12.318] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/ubuntu/buenComensalProject)
[2022-05-20 20:18:12.320] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-05-20 20:18:23.350] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: terminated by itself with code null, signal: SIGSEGV
[2022-05-20 20:46:06.215] [remoteagent] [info] [127.0.0.1][77b61f2b][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-05-20 20:46:06.336] [remoteagent] [info] [127.0.0.1][8700c5b7][ExtensionHostConnection] <164392> Extension Host Process exited with code: 0, signal: null.
